/**
 * Icon set — Phosphor.
 *
 * Every icon in the product is re-exported here, so the library is swappable
 * from one file. Phosphor sizes stroke by `weight` rather than `strokeWidth`;
 * `regular` is 1.5px on its 256-unit grid, which is the closest match to the
 * 1.75 optical weight we were using before. The default is set once via
 * `IconContext` in the app root rather than repeated on every element.
 */
export {
  AmazonLogo,
  ArrowClockwise,
  ArrowCounterClockwise,
  ArrowDownRight,
  ArrowSquareOut,
  ArrowUpRight,
  ArrowsClockwise,
  Broadcast,
  Buildings,
  CalendarDots,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  CaretUpDown,
  Check,
  CheckCircle,
  CircleNotch,
  Clock,
  ClockCounterClockwise,
  Cloud,
  Compass,
  Copy,
  CreditCard,
  Database,
  DotsThree,
  Funnel,
  Gauge,
  Gear,
  GitBranch,
  GitPullRequest,
  HardDrives,
  Heartbeat,
  Info,
  Kanban,
  Lifebuoy,
  MagnifyingGlass,
  MicrosoftOutlookLogo,
  MicrosoftTeamsLogo,
  Minus,
  Monitor,
  Moon,
  OpenAiLogo,
  Plug,
  Plugs,
  PlugsConnected,
  Plus,
  Prohibit,
  Pulse,
  Robot,
  Scroll,
  SealCheck,
  Shapes,
  ShareNetwork,
  SignOut,
  SlackLogo,
  Sliders,
  Sparkle,
  Speedometer,
  Sun,
  Target,
  Trash,
  TreeStructure,
  User,
  Users,
  Warning,
  WarningCircle,
  X,
} from "@phosphor-icons/react";

export type { Icon, IconWeight } from "@phosphor-icons/react";
